---
title: Work Experience
---

1. Software Engineering Internship - Atlassian (Mentor: Mr. Abhishek Patel, Senior Software Engineer)
    * Developed production-level code using Spring Boot Java, enabling data retrieval from Amazon DynamoDB and sending it to the data lake for Opsgenie.
    * Utilized Amazon SNS and SQS for real-time data updates, dynamically fetching user data and populating human-readable tables using SQL which was then used to create analysis charts for users.
    * Successfully debugged and tested the entire code using Splunk, ensuring functionality and efficiency before pushing it to production, aiming to save future costs by replacing an outsourced pipeline.
    * Recieved an offer letter to join as a Full-Time Software Engineer at Atlassian based on my work as an intern.

2. [Machine Unlearning: Forgetting Images](https://github.com/Inderjeet-23/Machine_Unlearning)
    * Implemented and explored various Machine Unlearning Algorithms to remove biased or sensitive data from Machine Learning systems, enhancing responsible practices and ethical deployment.
    * Conducted a thorough analysis of unlearning methods, including fine-tuning, resetting layers, noise injection and other, identifying suitable approaches for various practical use cases.
    * Evaluated the impact of unlearning methods on accuracy and time, optimizing hyperparameters to improve performance. Implemented basic biometric facial recognition system and tested our unlearning strategies on it.

3. [Bayesian Unlearning: Learning to Forget](https://github.com/Kalash0309/Bayesian_Unlearning)
    * Investigated Bayesian Unlearning methods to allow Probabilistic Machine Learning models to Unlearn specific data without full retraining, fostering adaptive and responsible models.
    * Employed mathematical approximations, including Laplace Approximation, Markov chain Monte Carlo Sampling, and Variational Inference, to achieve unlearning in Probabilistic models and assessed their performance.
    * Derived approximate closed form unlearning approach for logistic regression. Explored Unlearning for Neural Networks, analyzing different libraries' methods and hyperparameters, providing insights and direction for further research in Bayesian Unlearning. 